# static/admin/config.yml

backend:
  name: github
  repo: xkema/blog-demo-going-local-and-free-with-gatsby-and-netlify-cms
  branch: main

local_backend: true

media_folder: uploads

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: pages
    label: Pages
    folder: "src/pages"
    public_folder: ../../uploads
    create: true
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "page", required: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false, allow_multiple: false, choose_url: false}
  
  - name: designs
    label: Designs
    folder: "src/content/designs"
    public_folder: ../../../uploads
    create: true
    fields:
      - {label: "Content Key", name: "contentKey", widget: "hidden", default: "design", required: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", allow_multiple: false, choose_url: false}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image", allow_multiple: false, choose_url: false}

  - name: settings
    label: Settings
    description: General settings for the site
    files:
      - name: settings
        label: Settings
        file: src/content/settings.md
        fields:
          # - {label: "Content Key", name: "contentKey", widget: "hidden", default: "setting", required: true}
          # 👆 Hidden fields are not supported in "file" collections. This sections need to be added manually to the *.md files.
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {
              label: "Settings", name: "settings", widget: "object",
              fields: [
                {label: "Site Title", name: "siteTitle", widget: "string"},
                {label: "Email", name: "email", widget: "string", required: false},
                {label: "Phone", name: "phone", widget: "string", required: false},
                {label: "Facebook", name: "facebook", widget: "string", required: false},
                {label: "Twitter", name: "twitter", widget: "string", required: false},
                {label: "Youtube", name: "youtube", widget: "string", required: false},
                {label: "Address", name: "address", widget: "string", required: false},
                {label: "Business Name", name: "businessName", widget: "string", required: false},
              ]
            }
